name: Documentation
  
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.9.2'
      - uses: actions/checkout@v2
        with:
          repository: flavell-lab/FlavellBase.jl
          path: ./FlavellBase.jl
          token: ${{ secrets.GOLDENRATIO1618_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
        with:
          repository: flavell-lab/GPUFilter.jl
          path: ./GPUFilter.jl
          token: ${{ secrets.GOLDENRATIO1618_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
        with:
          repository: flavell-lab/MHDIO.jl
          path: ./MHDIO.jl
          token: ${{ secrets.GOLDENRATIO1618_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
        with:
          repository: flavell-lab/FFTRegGPU.jl
          path: ./FFTRegGPU.jl
          ref: main
          token: ${{ secrets.GOLDENRATIO1618_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
        with:
          repository: flavell-lab/NRRDIO.jl
          path: ./NRRDIO.jl
          ref: main
          token: ${{ secrets.GOLDENRATIO1618_ACCESS_TOKEN }}
      - name: Install Julia Python environment
        run: julia --project=docs/ -e 'using Pkg; 
          Pkg.add("PyCall");
          ENV["PYTHON"] = "";
          Pkg.build("PyCall");
          Pkg.add("PyPlot");
          Pkg.build("PyPlot");'
      - name: Install matplotlib
        run: ~/.julia/conda/3/x86_64/bin/pip install matplotlib
      - name: Install package
        run: julia --project=docs/ -e 'using Pkg; 
          Pkg.add(PackageSpec(path="./FlavellBase.jl"));
          Pkg.add(PackageSpec(path="./GPUFilter.jl"));
          Pkg.add(PackageSpec(path="./MHDIO.jl")); 
          Pkg.add(PackageSpec(path="./FFTRegGPU.jl"));
          Pkg.add(PackageSpec(path="./NRRDIO.jl"));
          Pkg.add(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl
